import React, { useState } from 'react';
import "./GenerateImageModal.css";

function GenerateImageModal({ onClose, onGenerateImage }) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmit = async (e) => {
    // e.preventDefault();
    // const token = localStorage.getItem('token');
    // try {
    //   const response = await fetch('https://localhost:8000/api/new_persona', {
    //     method: 'POST',
    //     headers: {
    //       'Content-Type': 'application/json',
    //       'Authorization': `Bearer ${token}`,
    //     },
    //     body: JSON.stringify({
    //         persona_name: name,
    //         persona_description: description }),
    //   });

    //   if (response.ok) {
    //     // Add the new persona with a default image
    //     onGenerateImage({ name, image: '/personas/default.png' });
    //     setName('');
    //     setDescription('');
    //     onClose();
    //   } else {
    //     console.error('Failed to create persona');
    //     alert('Failed to create persona. Please try again.');
    //   }
    // } catch (error) {
    //   console.error('Error creating persona:', error);
    //   alert('An error occurred. Please try again.');
    // }
  };

  return (
    <div className="modal-overlay">
      <div className="modal-content">
        <h2>Create New Persona</h2>
        <div className="form-container">
          <div className="form-group">
            <label htmlFor="image-description">Persona Description</label>
            <textarea
              id="image-description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              required
              placeholder="Image will be generated by AI according to this description:"
              rows="4"
            />
          </div>
          <div className="form-actions">
            <button type="button" onClick={handleSubmit}>
              Create
            </button>
            <button type="button" onClick={onClose}>
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default GenerateImageModal;